# Generated by Django 4.0.5 on 2022-06-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_desciption_movie_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='starts',
            new_name='stars',
        ),
    ]
